project:
  type: book
  output-dir: _book
  resources: 
    - assets/**     
    - downloads/**

book:
  title: "DAV Kursbuch - Frühsemester 2025"
  author: "Helena Jambor"
  date: "10/06/2025"
  chapters:
    - index.qmd
    - 01.qmd
    - 02.qmd
    - 03.qmd
    - 04.qmd
    - 05.qmd
    - 06.qmd
    - 07.qmd
    - 08.qmd
    - 09.qmd
    - 10.qmd
    - 11.qmd
    - 12.qmd
    - 13.qmd
    - 14.qmd
    - 15.qmd
    - 16.qmd
    - 17.qmd
    - 18.qmd
    - 19.qmd
    - 20.qmd
    - 22.qmd
    - 23.qmd
    - 25.qmd
    - 26.qmd
    - 28.qmd
    - 30.qmd
    - 35.qmd
    - summary.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true

  pdf:
    fig-dpi: 150        # or 120; default is 300
    pdf-engine: xelatex
    toc: true


editor: source
